[build]
builder = "nixpacks"
buildCommand = "npm cache clean --force && npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://plango-api-production.up.railway.app/api/v1" 